// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
)

// The response error.
// Ref: #/components/schemas/Error
type GetConfigurationBadGateway struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetConfigurationBadGateway) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetConfigurationBadGateway) getConfigurationRes() {}

// The response error.
// Ref: #/components/schemas/Error
type GetConfigurationBadRequest struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetConfigurationBadRequest) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetConfigurationBadRequest) getConfigurationRes() {}

// The response error.
// Ref: #/components/schemas/Error
type GetConfigurationGatewayTimeout struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetConfigurationGatewayTimeout) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetConfigurationGatewayTimeout) getConfigurationRes() {}

// The response error.
// Ref: #/components/schemas/Error
type GetConfigurationInternalServerError struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetConfigurationInternalServerError) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetConfigurationInternalServerError) getConfigurationRes() {}

// The response error.
// Ref: #/components/schemas/Error
type GetConfigurationNotFound struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetConfigurationNotFound) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetConfigurationNotFound) getConfigurationRes() {}

type GetConfigurationOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetConfigurationOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// GetConfigurationOKHeaders wraps GetConfigurationOK with response headers.
type GetConfigurationOKHeaders struct {
	ConfigurationVersion OptString
	ContentType          string
	Response             GetConfigurationOK
}

// GetConfigurationVersion returns the value of ConfigurationVersion.
func (s *GetConfigurationOKHeaders) GetConfigurationVersion() OptString {
	return s.ConfigurationVersion
}

// GetContentType returns the value of ContentType.
func (s *GetConfigurationOKHeaders) GetContentType() string {
	return s.ContentType
}

// GetResponse returns the value of Response.
func (s *GetConfigurationOKHeaders) GetResponse() GetConfigurationOK {
	return s.Response
}

// SetConfigurationVersion sets the value of ConfigurationVersion.
func (s *GetConfigurationOKHeaders) SetConfigurationVersion(val OptString) {
	s.ConfigurationVersion = val
}

// SetContentType sets the value of ContentType.
func (s *GetConfigurationOKHeaders) SetContentType(val string) {
	s.ContentType = val
}

// SetResponse sets the value of Response.
func (s *GetConfigurationOKHeaders) SetResponse(val GetConfigurationOK) {
	s.Response = val
}

func (*GetConfigurationOKHeaders) getConfigurationRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
