// Code generated by ogen, DO NOT EDIT.

package appconfigagentapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetConfigurationOperation OperationName = "GetConfiguration"
)
