// Code generated by ogen, DO NOT EDIT.

package appconfigagentapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetConfiguration implements getConfiguration operation.
//
// GET /applications/{Application}/environments/{Environment}/configurations/{Configuration}
func (UnimplementedHandler) GetConfiguration(ctx context.Context, params GetConfigurationParams) (r GetConfigurationRes, _ error) {
	return r, ht.ErrNotImplemented
}
