// Code generated by ogen, DO NOT EDIT.

package apiv2

// OperationName is the ogen operation name
type OperationName = string

const (
	GetConfigurationOperation OperationName = "GetConfiguration"
)
