// Code generated by ogen, DO NOT EDIT.

package apiv2

// GetConfigurationParams is parameters of getConfiguration operation.
type GetConfigurationParams struct {
	// The application for the configuration to get. Specify either the application name or the
	// application ID.
	Application string
	// The environment for the configuration to get. Specify either the environment name or the
	// environment ID.
	Environment string
	// The configuration to get. Specify either the configuration name or the configuration ID.
	Configuration string
	// The flag names of feature flag configuration.
	Flag []string
	// The evaluation context for feature flag configuration.
	Context []string
}
