name: test-go

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        required: true
      go-cache:
        type: boolean
        default: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: ${{ inputs.go-cache }}
      - uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout=10m
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          cache: ${{ inputs.go-cache }}
      - uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('appconfigagentv2/testcontainers_test.go') }}
      - run: |
          go install github.com/mfridman/tparse@latest
      - run: |
          set -o pipefail
          go test ./... -count=1 -cover -json | tee ./go-test.out | tparse -all
      - if: always()
        run: |
          tparse -file ./go-test.out -format markdown >> "$GITHUB_STEP_SUMMARY"
